version: '3'

services:
  web:
    build: ./resume_parser
    command: sh -c "python /usr/src/app/manage.py migrate && gunicorn resume_parser.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./resume_parser/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - "8000"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - "8080:8000"   # guest:host
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:

